'use client';
import { useMemo, useState } from 'react';
import { downloadInvoicePdf } from '../../lib/pdf-generator';

type Item = { description: string; qty: number; rate: number };

export default function InvoiceGenerator(){
 const [business,setBusiness]=useState('Your Business'); const [client,setClient]=useState('Client Name'); const [currency,setCurrency]=useState('$');
 const [number,setNumber]=useState('INV-1001'); const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [dueDate,setDueDate]=useState('');
 const [items,setItems]=useState<Item[]>([{description:'Service',qty:1,rate:100}]); const [tax,setTax]=useState(0); const [discount,setDiscount]=useState(0);
 const subtotal=useMemo(()=>items.reduce((s,i)=>s+Math.max(0,i.qty)*Math.max(0,i.rate),0),[items]); const taxable=Math.max(0,subtotal-discount); const taxAmount=taxable*tax/100; const total=Math.max(0,taxable+taxAmount);
 const updateItem=(n:number,key:keyof Item,value:string)=>{const a=[...items]; if(key==='description') a[n].description=value; else a[n][key]=Math.max(0,Number(value)); setItems(a)};
 const add=()=>setItems([...items,{description:'New item',qty:1,rate:0}]);
 const remove=(n:number)=>setItems(items.filter((_,i)=>i!==n));
 const pdf=()=>downloadInvoicePdf({business,client,currency,number,date,dueDate,items,subtotal,discount,tax,total});
 return <main className="generator"><header className="nav"><div className="brand">Invoice<span>Flow</span></div><a href="/">← Home</a></header><div className="gen-grid"><section className="form-panel"><h1>Create Invoice</h1><label>Business name<input value={business} onChange={e=>setBusiness(e.target.value)}/></label><label>Client name<input value={client} onChange={e=>setClient(e.target.value)}/></label><div className="twocol"><label>Invoice #<input value={number} onChange={e=>setNumber(e.target.value)}/></label><label>Currency<select value={currency} onChange={e=>setCurrency(e.target.value)}><option>$</option><option>€</option><option>£</option><option>₨</option><option>د.إ</option><option>C$</option><option>A$</option></select></label></div><div className="twocol"><label>Issue date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Due date<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label></div><h2>Items</h2>{items.map((item,n)=><div className="item" key={n}><input aria-label="Description" value={item.description} onChange={e=>updateItem(n,'description',e.target.value)}/><input aria-label="Quantity" type="number" min="0" value={item.qty} onChange={e=>updateItem(n,'qty',e.target.value)}/><input aria-label="Rate" type="number" min="0" value={item.rate} onChange={e=>updateItem(n,'rate',e.target.value)}/>{items.length>1&&<button type="button" className="remove" onClick={()=>remove(n)}>×</button>}</div>)}<button type="button" className="btn secondary" onClick={add}>+ Add item</button><div className="twocol"><label>Discount<input type="number" min="0" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></label><label>Tax %<input type="number" min="0" value={tax} onChange={e=>setTax(Number(e.target.value))}/></label></div></section><section className="preview"><div className="paper"><div className="invoice-top"><b>INVOICE</b><span>#{number}</span></div><p><b>{business}</b><br/>Bill to: {client}<br/>Issue: {date}{dueDate&&<> · Due: {dueDate}</>}</p><hr/>{items.map((i,n)=><div className="invoice-row" key={n}><span>{i.description} × {i.qty}</span><b>{currency}{(i.qty*i.rate).toFixed(2)}</b></div>)}<hr/><div className="invoice-row"><span>Subtotal</span><b>{currency}{subtotal.toFixed(2)}</b></div><div className="invoice-row"><span>Discount</span><b>-{currency}{discount.toFixed(2)}</b></div><div className="invoice-row"><span>Tax</span><b>{currency}{taxAmount.toFixed(2)}</b></div><div className="invoice-total"><span>Total</span><b>{currency}{total.toFixed(2)}</b></div></div><div className="preview-actions"><button className="btn primary" onClick={()=>window.print()}>Print Invoice</button><button className="btn secondary" onClick={pdf}>Download PDF</button></div></section></div></main>
}