'use client';
import { useMemo, useState } from 'react';

export default function InvoiceGenerator(){
 const [business,setBusiness]=useState('Your Business'); const [client,setClient]=useState('Client Name'); const [currency,setCurrency]=useState('$');
 const [items,setItems]=useState([{description:'Service',qty:1,rate:100}]); const [tax,setTax]=useState(0); const [discount,setDiscount]=useState(0);
 const subtotal=useMemo(()=>items.reduce((s,i)=>s+i.qty*i.rate,0),[items]); const total=Math.max(0,subtotal-discount+(subtotal-discount)*tax/100);
 const add=()=>setItems([...items,{description:'New item',qty:1,rate:0}]);
 return <main className="generator"><header className="nav"><div className="brand">Invoice<span>Flow</span></div><a href="/">← Home</a></header><div className="gen-grid"><section className="form-panel"><h1>Create Invoice</h1><label>Business name<input value={business} onChange={e=>setBusiness(e.target.value)}/></label><label>Client name<input value={client} onChange={e=>setClient(e.target.value)}/></label><label>Currency<select value={currency} onChange={e=>setCurrency(e.target.value)}><option>$</option><option>€</option><option>£</option><option>₨</option><option>د.إ</option></select></label><h2>Items</h2>{items.map((item,n)=><div className="item" key={n}><input value={item.description} onChange={e=>{const a=[...items];a[n].description=e.target.value;setItems(a)}}/><input type="number" min="0" value={item.qty} onChange={e=>{const a=[...items];a[n].qty=Number(e.target.value);setItems(a)}}/><input type="number" min="0" value={item.rate} onChange={e=>{const a=[...items];a[n].rate=Number(e.target.value);setItems(a)}}/></div>)}<button className="btn secondary" onClick={add}>+ Add item</button><div className="twocol"><label>Discount<input type="number" min="0" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></label><label>Tax %<input type="number" min="0" value={tax} onChange={e=>setTax(Number(e.target.value))}/></label></div></section><section className="preview"><div className="paper"><div className="invoice-top"><b>INVOICE</b><span>#INV-1001</span></div><p><b>{business}</b><br/>Bill to: {client}</p><hr/>{items.map((i,n)=><div className="invoice-row" key={n}><span>{i.description} × {i.qty}</span><b>{currency}{(i.qty*i.rate).toFixed(2)}</b></div>)}<hr/><div className="invoice-row"><span>Subtotal</span><b>{currency}{subtotal.toFixed(2)}</b></div><div className="invoice-row"><span>Discount</span><b>-{currency}{discount.toFixed(2)}</b></div><div className="invoice-row"><span>Tax</span><b>{currency}{((subtotal-discount)*tax/100).toFixed(2)}</b></div><div className="invoice-total"><span>Total</span><b>{currency}{total.toFixed(2)}</b></div></div><div className="preview-actions"><button className="btn primary" onClick={()=>window.print()}>Print Invoice</button><button className="btn secondary" disabled title="PDF export is next build step">Download PDF</button></div></section></div></main>
}